package it.richkmeli.richkware.storage;

public enum StorageKey {
    RND_TEST,
    DEVICE_ID,
    INSTALLATION_ID,
    NETWORK_PROTOCOL,
    NETWORK_SERVER,
    NETWORK_SERVICE,
    NETWORK_APPLICATION_SERVICE,
    LOCATION, DEVICE_ADMIN, BATTERY_STATUS, POWER_STATUS;
}
